### ISSUE TITLE
no minibuffer history for /

### ISSUE THREAD

**Issue by unhammer** [edkolev/evil-lion#12]
Whenever I use `/`, the minibuffer suggests `/` as the default instead of what I last used. Ie. do `glap/-- RET` and then `glap/` and it'll show `Pattern [/]:` instead of `Pattern [--]:`

**Comment by edkolev** [comment]
It took me a while to get to this, but it's finally done: https://github.com/edkolev/evil-lion/commit/dcd5d11f80c843387d33f9728f87f79748636837

The history functionality is simple - the history will not be remembered b/w emacs sessions and only one pattern will be remembered (no history with `M-n`/`M-p`).

Please let me know in case this doesn't work for you.

**Comment by unhammer** [comment]
That sure helps ,but why not use the HISTORY argument and a list? Something like

```

(defvar evil-lion--prev-user-regex '("/")
  "The last regexes used for alignment, specified by the user.")

(defun evil-lion--maybe-read-regex (char)
  "If CHAR is \"/\", ask the user for a regex. Otherwise regexp-quote CHAR."
  (if (eq char ?/)
      (let* ((default (if evil-lion--prev-user-regex
                          (car evil-lion--prev-user-regex)
                        "/"))
             (regex (read-string (format "Pattern [%s]: " default)
                                nil
                                'evil-lion--prev-user-regex
                                default)))
        (progn (push regex evil-lion--prev-user-regex)
               regex))
    (regexp-quote (format  "%c" char))))
```

**Comment by edkolev** [comment]
This is great, thank you!
