### ISSUE TITLE
allow controlling repeatability like vim-easy-align 

### ISSUE THREAD

**Issue by ninrod** [edkolev/evil-lion#9]
hi again @edkolev.

your awesome package is very close to mimic [vim-easy-align](https://github.com/junegunn/vim-easy-align) in functionality. One functionality I miss comming from vim is the `gaip*=` vs `gaip=` where I can control the repeatability of the pattern, like this [demo](https://raw.githubusercontent.com/junegunn/i/master/easy-align/equals.gif).

consider adding said functionality.

**Comment by edkolev** [comment]
Hi!

This is a great suggestion! Here's a quick comparison between vim-easy-align and vim-lion user interfaces:

vim-easy-align:
- `ga ip =` Around the 1st occurrences
- `ga ip 2=` Around the 2nd occurrences
- `ga ip *=` Around all occurrences

vim-lion:
- `1 gl ip =` 1st occurrence
- `2 gl ip =` 1st & 2nd occurrences
- `gl ip =` all occurrences

Most notably, they take the count differently.

I'm more inclined to follow vim-lion's interface, I find it more in-line with other vim operators, which typically work as `[count] operator {motion}`. vim-easy-align instead works as `operator {motion} interactively-prompt-user`.

**Comment by ninrod** [comment]
Ow, I did not know that. So there you go, there's already a way to do that. My search is complete. Thank you sir!

**Comment by edkolev** [comment]
You're very welcome :)
